gfx/env/52h03bk.tga
gfx/env/52h03dn.tga
gfx/env/52h03ft.tga
gfx/env/52h03lf.tga
gfx/env/52h03rt.tga
gfx/env/52h03up.tga
models/anubis.mdl
models/bush_plant2_small.mdl
models/de_anubis_big_bottle2.mdl
models/de_anubis_ecoffer1.mdl
models/egypt_collone_small.mdl
models/fakel_x1.mdl
models/palme.mdl
models/S_ENV_LooseRope02.mdl
models/zyn_kingtut.mdl
sound/ambience/rain.wav
sound/ambience/thunder_clap.wav
sound/ambience/waterrun.wav
sprites/fire2.spr
maps/ze_egipto_ng.res
