//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/zm_atix_helicopter.html
halflife.wad
gfx/env/atix_bk.tga
gfx/env/atix_ft.tga
gfx/env/atix_lf.tga
gfx/env/atix_rt.tga
gfx/env/atix_up.tga
sound/zm_atix_helicopter/scream.wav
sound/zm_atix_helicopter/fon.wav
sound/zm_atix_helicopter/atix.wav
sound/zm_atix_helicopter/helicopter.wav
sound/zm_atix_helicopter/plane.wav
sound/zm_atix_helicopter/explode.wav
gfx/env/atix_dn.tga
maps/zm_atix_helicopter.bsp
maps/zm_atix_helicopter.txt
